### ISSUE TITLE
code nft_market_place_address on logic.js

### ISSUE THREAD

**Issue by gunomnifluencer** [DanielMoralisSamples/25_NFT_MARKET_PLACE#3]
Hello,

I've tried your github, but why there is no code for : **nft_market_place_address** ?
on the comments marks it's written : _//NFT Market Place Contract, code of this contract is in the following github repository https://github.com/DanielMoralisSamples/25_NFT_MARKET_PLACE._

But I didn't find it, could you help me?

Thanks

**Comment by Daniel-Itzul** [comment]
Sure, there are two contracts needed for this project.

Both are in the contracts folder of this repo.

The NFT MarketPlace contract is here:
https://github.com/DanielMoralisSamples/25_NFT_MARKET_PLACE/blob/master/contracts/market_place.sol

The other contract can be found here:
https://github.com/DanielMoralisSamples/25_NFT_MARKET_PLACE/blob/master/contracts/nft_contract.sol

To get an address for them you need to deploy them.

I recommend remix.
