### ISSUE TITLE
market_place.sol  doesn't support royalties (EIP2981)

### ISSUE THREAD

**Issue by DoDzilla-ai** [DanielMoralisSamples/25_NFT_MARKET_PLACE#4]
The title explains everything. I've deployed the market_place.sol and an ERC721 contract on Remix. Minted, listed, and sold an NFT with EIP2981 complient NFT contract but the royalty recipient didn't receive anything and the seller received everything.  I think this is needed since the EIP2981 is an industry-standard at the moment. The ERC 721 NFT contract (with EIP2981 support) can be found here: https://github.com/dievardump/EIP2981-implementation/blob/main/contracts/mocks/ERC721WithRoyalties.sol

**Comment by Daniel-Itzul** [comment]
Hi DoDzilla-ai, this is contract is merely for learning purposes, not for specific use cases. But I might cover that in future tutorials.
